// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SOA-1-model/src/main/java/pl/edu/agh/soa/lab1/addressbook.proto

package protobuf;

public final class LegoSetsProtoBuf {
  private LegoSetsProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LegoSetIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.edu.agh.soa.lab1.LegoSetId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 legoSetId = 1;</code>
     */
    boolean hasLegoSetId();
    /**
     * <code>required int32 legoSetId = 1;</code>
     */
    int getLegoSetId();
  }
  /**
   * Protobuf type {@code pl.edu.agh.soa.lab1.LegoSetId}
   */
  public  static final class LegoSetId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.edu.agh.soa.lab1.LegoSetId)
      LegoSetIdOrBuilder {
    // Use LegoSetId.newBuilder() to construct.
    private LegoSetId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LegoSetId() {
      legoSetId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LegoSetId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              legoSetId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LegoSetId.class, Builder.class);
    }

    private int bitField0_;
    public static final int LEGOSETID_FIELD_NUMBER = 1;
    private int legoSetId_;
    /**
     * <code>required int32 legoSetId = 1;</code>
     */
    public boolean hasLegoSetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 legoSetId = 1;</code>
     */
    public int getLegoSetId() {
      return legoSetId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLegoSetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, legoSetId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, legoSetId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LegoSetId)) {
        return super.equals(obj);
      }
      LegoSetId other = (LegoSetId) obj;

      boolean result = true;
      result = result && (hasLegoSetId() == other.hasLegoSetId());
      if (hasLegoSetId()) {
        result = result && (getLegoSetId()
            == other.getLegoSetId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLegoSetId()) {
        hash = (37 * hash) + LEGOSETID_FIELD_NUMBER;
        hash = (53 * hash) + getLegoSetId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LegoSetId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LegoSetId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LegoSetId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LegoSetId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LegoSetId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LegoSetId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LegoSetId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LegoSetId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LegoSetId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LegoSetId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LegoSetId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.edu.agh.soa.lab1.LegoSetId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.edu.agh.soa.lab1.LegoSetId)
        LegoSetIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LegoSetId.class, Builder.class);
      }

      // Construct using protobuf.LegoSetsProtoBuf.LegoSetId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        legoSetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor;
      }

      public LegoSetId getDefaultInstanceForType() {
        return LegoSetId.getDefaultInstance();
      }

      public LegoSetId build() {
        LegoSetId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LegoSetId buildPartial() {
        LegoSetId result = new LegoSetId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.legoSetId_ = legoSetId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LegoSetId) {
          return mergeFrom((LegoSetId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LegoSetId other) {
        if (other == LegoSetId.getDefaultInstance()) return this;
        if (other.hasLegoSetId()) {
          setLegoSetId(other.getLegoSetId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLegoSetId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LegoSetId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LegoSetId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int legoSetId_ ;
      /**
       * <code>required int32 legoSetId = 1;</code>
       */
      public boolean hasLegoSetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 legoSetId = 1;</code>
       */
      public int getLegoSetId() {
        return legoSetId_;
      }
      /**
       * <code>required int32 legoSetId = 1;</code>
       */
      public Builder setLegoSetId(int value) {
        bitField0_ |= 0x00000001;
        legoSetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 legoSetId = 1;</code>
       */
      public Builder clearLegoSetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        legoSetId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.edu.agh.soa.lab1.LegoSetId)
    }

    // @@protoc_insertion_point(class_scope:pl.edu.agh.soa.lab1.LegoSetId)
    private static final LegoSetId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LegoSetId();
    }

    public static LegoSetId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<LegoSetId>
        PARSER = new com.google.protobuf.AbstractParser<LegoSetId>() {
      public LegoSetId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LegoSetId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LegoSetId> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LegoSetId> getParserForType() {
      return PARSER;
    }

    public LegoSetId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LegoSetsIdProtoBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    java.util.List<LegoSetId>
        getLegoSetIdList();
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    LegoSetId getLegoSetId(int index);
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    int getLegoSetIdCount();
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    java.util.List<? extends LegoSetIdOrBuilder>
        getLegoSetIdOrBuilderList();
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    LegoSetIdOrBuilder getLegoSetIdOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf}
   */
  public  static final class LegoSetsIdProtoBuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf)
      LegoSetsIdProtoBufOrBuilder {
    // Use LegoSetsIdProtoBuf.newBuilder() to construct.
    private LegoSetsIdProtoBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LegoSetsIdProtoBuf() {
      legoSetId_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LegoSetsIdProtoBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                legoSetId_ = new java.util.ArrayList<LegoSetId>();
                mutable_bitField0_ |= 0x00000001;
              }
              legoSetId_.add(
                  input.readMessage(LegoSetId.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          legoSetId_ = java.util.Collections.unmodifiableList(legoSetId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LegoSetsIdProtoBuf.class, Builder.class);
    }

    public static final int LEGOSETID_FIELD_NUMBER = 1;
    private java.util.List<LegoSetId> legoSetId_;
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    public java.util.List<LegoSetId> getLegoSetIdList() {
      return legoSetId_;
    }
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    public java.util.List<? extends LegoSetIdOrBuilder>
        getLegoSetIdOrBuilderList() {
      return legoSetId_;
    }
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    public int getLegoSetIdCount() {
      return legoSetId_.size();
    }
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    public LegoSetId getLegoSetId(int index) {
      return legoSetId_.get(index);
    }
    /**
     * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
     */
    public LegoSetIdOrBuilder getLegoSetIdOrBuilder(
        int index) {
      return legoSetId_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLegoSetIdCount(); i++) {
        if (!getLegoSetId(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < legoSetId_.size(); i++) {
        output.writeMessage(1, legoSetId_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < legoSetId_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, legoSetId_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LegoSetsIdProtoBuf)) {
        return super.equals(obj);
      }
      LegoSetsIdProtoBuf other = (LegoSetsIdProtoBuf) obj;

      boolean result = true;
      result = result && getLegoSetIdList()
          .equals(other.getLegoSetIdList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLegoSetIdCount() > 0) {
        hash = (37 * hash) + LEGOSETID_FIELD_NUMBER;
        hash = (53 * hash) + getLegoSetIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LegoSetsIdProtoBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LegoSetsIdProtoBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LegoSetsIdProtoBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LegoSetsIdProtoBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LegoSetsIdProtoBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LegoSetsIdProtoBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LegoSetsIdProtoBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LegoSetsIdProtoBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LegoSetsIdProtoBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LegoSetsIdProtoBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LegoSetsIdProtoBuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf)
        LegoSetsIdProtoBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LegoSetsIdProtoBuf.class, Builder.class);
      }

      // Construct using protobuf.LegoSetsProtoBuf.LegoSetsIdProtoBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLegoSetIdFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (legoSetIdBuilder_ == null) {
          legoSetId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          legoSetIdBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LegoSetsProtoBuf.internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor;
      }

      public LegoSetsIdProtoBuf getDefaultInstanceForType() {
        return LegoSetsIdProtoBuf.getDefaultInstance();
      }

      public LegoSetsIdProtoBuf build() {
        LegoSetsIdProtoBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LegoSetsIdProtoBuf buildPartial() {
        LegoSetsIdProtoBuf result = new LegoSetsIdProtoBuf(this);
        int from_bitField0_ = bitField0_;
        if (legoSetIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            legoSetId_ = java.util.Collections.unmodifiableList(legoSetId_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.legoSetId_ = legoSetId_;
        } else {
          result.legoSetId_ = legoSetIdBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LegoSetsIdProtoBuf) {
          return mergeFrom((LegoSetsIdProtoBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LegoSetsIdProtoBuf other) {
        if (other == LegoSetsIdProtoBuf.getDefaultInstance()) return this;
        if (legoSetIdBuilder_ == null) {
          if (!other.legoSetId_.isEmpty()) {
            if (legoSetId_.isEmpty()) {
              legoSetId_ = other.legoSetId_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLegoSetIdIsMutable();
              legoSetId_.addAll(other.legoSetId_);
            }
            onChanged();
          }
        } else {
          if (!other.legoSetId_.isEmpty()) {
            if (legoSetIdBuilder_.isEmpty()) {
              legoSetIdBuilder_.dispose();
              legoSetIdBuilder_ = null;
              legoSetId_ = other.legoSetId_;
              bitField0_ = (bitField0_ & ~0x00000001);
              legoSetIdBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLegoSetIdFieldBuilder() : null;
            } else {
              legoSetIdBuilder_.addAllMessages(other.legoSetId_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLegoSetIdCount(); i++) {
          if (!getLegoSetId(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LegoSetsIdProtoBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LegoSetsIdProtoBuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<LegoSetId> legoSetId_ =
        java.util.Collections.emptyList();
      private void ensureLegoSetIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          legoSetId_ = new java.util.ArrayList<LegoSetId>(legoSetId_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LegoSetId, LegoSetId.Builder, LegoSetIdOrBuilder> legoSetIdBuilder_;

      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public java.util.List<LegoSetId> getLegoSetIdList() {
        if (legoSetIdBuilder_ == null) {
          return java.util.Collections.unmodifiableList(legoSetId_);
        } else {
          return legoSetIdBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public int getLegoSetIdCount() {
        if (legoSetIdBuilder_ == null) {
          return legoSetId_.size();
        } else {
          return legoSetIdBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public LegoSetId getLegoSetId(int index) {
        if (legoSetIdBuilder_ == null) {
          return legoSetId_.get(index);
        } else {
          return legoSetIdBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder setLegoSetId(
          int index, LegoSetId value) {
        if (legoSetIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegoSetIdIsMutable();
          legoSetId_.set(index, value);
          onChanged();
        } else {
          legoSetIdBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder setLegoSetId(
          int index, LegoSetId.Builder builderForValue) {
        if (legoSetIdBuilder_ == null) {
          ensureLegoSetIdIsMutable();
          legoSetId_.set(index, builderForValue.build());
          onChanged();
        } else {
          legoSetIdBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder addLegoSetId(LegoSetId value) {
        if (legoSetIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegoSetIdIsMutable();
          legoSetId_.add(value);
          onChanged();
        } else {
          legoSetIdBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder addLegoSetId(
          int index, LegoSetId value) {
        if (legoSetIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegoSetIdIsMutable();
          legoSetId_.add(index, value);
          onChanged();
        } else {
          legoSetIdBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder addLegoSetId(
          LegoSetId.Builder builderForValue) {
        if (legoSetIdBuilder_ == null) {
          ensureLegoSetIdIsMutable();
          legoSetId_.add(builderForValue.build());
          onChanged();
        } else {
          legoSetIdBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder addLegoSetId(
          int index, LegoSetId.Builder builderForValue) {
        if (legoSetIdBuilder_ == null) {
          ensureLegoSetIdIsMutable();
          legoSetId_.add(index, builderForValue.build());
          onChanged();
        } else {
          legoSetIdBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder addAllLegoSetId(
          Iterable<? extends LegoSetId> values) {
        if (legoSetIdBuilder_ == null) {
          ensureLegoSetIdIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, legoSetId_);
          onChanged();
        } else {
          legoSetIdBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder clearLegoSetId() {
        if (legoSetIdBuilder_ == null) {
          legoSetId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          legoSetIdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public Builder removeLegoSetId(int index) {
        if (legoSetIdBuilder_ == null) {
          ensureLegoSetIdIsMutable();
          legoSetId_.remove(index);
          onChanged();
        } else {
          legoSetIdBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public LegoSetId.Builder getLegoSetIdBuilder(
          int index) {
        return getLegoSetIdFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public LegoSetIdOrBuilder getLegoSetIdOrBuilder(
          int index) {
        if (legoSetIdBuilder_ == null) {
          return legoSetId_.get(index);  } else {
          return legoSetIdBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public java.util.List<? extends LegoSetIdOrBuilder>
           getLegoSetIdOrBuilderList() {
        if (legoSetIdBuilder_ != null) {
          return legoSetIdBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(legoSetId_);
        }
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public LegoSetId.Builder addLegoSetIdBuilder() {
        return getLegoSetIdFieldBuilder().addBuilder(
            LegoSetId.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public LegoSetId.Builder addLegoSetIdBuilder(
          int index) {
        return getLegoSetIdFieldBuilder().addBuilder(
            index, LegoSetId.getDefaultInstance());
      }
      /**
       * <code>repeated .pl.edu.agh.soa.lab1.LegoSetId legoSetId = 1;</code>
       */
      public java.util.List<LegoSetId.Builder>
           getLegoSetIdBuilderList() {
        return getLegoSetIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LegoSetId, LegoSetId.Builder, LegoSetIdOrBuilder>
          getLegoSetIdFieldBuilder() {
        if (legoSetIdBuilder_ == null) {
          legoSetIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LegoSetId, LegoSetId.Builder, LegoSetIdOrBuilder>(
                  legoSetId_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          legoSetId_ = null;
        }
        return legoSetIdBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf)
    }

    // @@protoc_insertion_point(class_scope:pl.edu.agh.soa.lab1.LegoSetsIdProtoBuf)
    private static final LegoSetsIdProtoBuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LegoSetsIdProtoBuf();
    }

    public static LegoSetsIdProtoBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<LegoSetsIdProtoBuf>
        PARSER = new com.google.protobuf.AbstractParser<LegoSetsIdProtoBuf>() {
      public LegoSetsIdProtoBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LegoSetsIdProtoBuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LegoSetsIdProtoBuf> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LegoSetsIdProtoBuf> getParserForType() {
      return PARSER;
    }

    public LegoSetsIdProtoBuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_edu_agh_soa_lab1_LegoSetId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n?SOA-1-model/src/main/java/pl/edu/agh/s" +
      "oa/lab1/addressbook.proto\022\023pl.edu.agh.so" +
      "a.lab1\"\036\n\tLegoSetId\022\021\n\tlegoSetId\030\001 \002(\005\"G" +
      "\n\022LegoSetsIdProtoBuf\0221\n\tlegoSetId\030\001 \003(\0132" +
      "\036.pl.edu.agh.soa.lab1.LegoSetIdB\034\n\010proto" +
      "bufB\020LegoSetsProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_edu_agh_soa_lab1_LegoSetId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_edu_agh_soa_lab1_LegoSetId_descriptor,
        new String[] { "LegoSetId", });
    internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_edu_agh_soa_lab1_LegoSetsIdProtoBuf_descriptor,
        new String[] { "LegoSetId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
